
namespace DeepSigma.AutoML.Enums.StateSpace;

/// <summary>
/// StateSpaceModel is an enumeration that defines different types of state space models, which are mathematical frameworks used to model dynamic systems and processes in various fields such as control systems, signal processing, time series analysis, and economic forecasting, where the underlying state of the system is not directly observable but can be inferred from observed data through a set of equations that describe the evolution of the system over time, allowing for accurate estimation and prediction of the system's behavior even in the presence of noise and uncertainty in the data.
/// </summary>
public enum StateSpaceModel
{
    /// <summary>
    /// KalmanFilter is a state space model that uses a recursive algorithm to estimate the state of a linear dynamic system from a series of noisy measurements, providing optimal estimates of the system's state by minimizing the mean squared error between the estimated and true states, making it widely used in various applications such as control systems, signal processing, and time series analysis where accurate state estimation is crucial for decision-making and prediction tasks.
    /// Often used in economic forecasting, where the model can learn to estimate the underlying state of the economy based on noisy and incomplete data, improving its ability to make accurate predictions and inform policy decisions even in the presence of uncertainty and volatility in economic indicators.
    /// </summary>
    KalmanFilter,
    /// <summary>
    /// HiddenMarkovModel is a state space model that represents a system as a Markov process with hidden states, where the observed data is generated by the hidden states through a probabilistic emission process, allowing for the modeling of sequential data and temporal dependencies in various applications such as speech recognition, natural language processing, and time series analysis, where the underlying state of the system is not directly observable but can be inferred from the observed data.
    /// In economic forecasting, Hidden Markov Models can be used to model the underlying state of the economy, such as different economic regimes or market conditions, based on observed economic indicators, allowing for improved predictions and insights into the dynamics of the economy even when the true state is not directly observable.
    /// </summary>
    HiddenMarkovModel,
    /// <summary>
    /// BaysianStructuralTimeSeriesModel is a state space model that combines Bayesian inference with structural time series modeling to capture complex temporal patterns and dependencies in time series data, allowing for the incorporation of prior knowledge and uncertainty into the modeling process, making it particularly effective for forecasting and analyzing time series data in various domains such as economics, finance, and environmental science, where understanding the underlying structure of the data is crucial for accurate predictions and decision-making.
    /// In economic forecasting, Bayesian Structural Time Series Models can be used to model the underlying structure of economic data, such as trends, seasonality, and other temporal patterns, while also incorporating prior knowledge and uncertainty into the modeling process, leading to improved forecasts and insights into the dynamics of the economy even in the presence of noisy and volatile data.
    /// </summary>
    BaysianStructuralTimeSeriesModel
}
